#! /bin/sh


case "$1" in
start)
echo "Starting init script for I2C module"
modprobe i2c-dev
modprobe i2c-bcm2835
modprobe spidev
modprobe spi-bcm2835
modprobe hci_uart
hciattach /dev/ttyS0 bcm43xx 115200 noflow -
hciconfig hic0 up
/usr/libexec/bluetooth/bluetoothd -E &
controller &
/root/GATT_Advertise
;;
stop)
echo "Removing user modules"
rmmod i2c-bcm2835
rmmod i2c-dev
;;
*)
echo "Usage: $0 {start|stop}"
exit 1
esac
exit 0
