#!/usr/bin/env python3

import posix_ipc

# Create the message queue.
mq = posix_ipc.MessageQueue("/my_mq")


try:
    while(1):
        string = input('type in things')
        mq.send(string)
except KeyboardInterrupt:
    print('handle the exit')
    mq.close()
    #mq.unlink()
    
    
